[platformio]
extra_configs = platformio_override.ini

[env]
platform = espressif32
framework = arduino
upload_speed = 921600
monitor_speed = 115200
upload_protocol = esptool

lib_deps =
    bodmer/TFT_eSPI@^2.5.30
    https://github.com/PaulStoffregen/XPT2046_Touchscreen@^1.4.0
    ; h2zero/NimBLE-Arduino ; BLE library - Enabling BLE will increase the firmware size significantly
    lua@^0.1.1
    links2004/WebSockets@^2.7.1
    bblanchon/ArduinoJson@^7.4.2

build_flags =

    ; Fonts
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1

    -D USE_HSPI_PORT=1
    -D SPI_FREQUENCY=40000000L ; Dangerous


[env:HMI]
board = esp32-s3-devkitc-1
monitor_filters = esp32_exception_decoder
build_flags =
    ${env.build_flags}

    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D BOARD_HAS_PSRAM
    
    -D PWR_EN_PIN=10
    -D PWR_ON_PIN=14    
    
    -D USER_SETUP_LOADED=1
    -include $PROJECT_LIBDEPS_DIR/$PIOENV/TFT_eSPI/User_Setups/Setup207_LilyGo_T_HMI.h

board_build.arduino.memory_type = qio_opi

[env:esp32dev]
board = esp32dev
board_build.filesystem = spiffs
board_build.partitions = no_ota.csv

build_flags =
    ${env.build_flags}
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_RGB_ORDER=TFT_RGB

    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=4

    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH

    -D TOUCH_CS=33
    -D TOUCH_IRQ=36